server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info

spring:
  application:
    name: config-client
  config:
    import: "optional:configserver:http://localhost:8088/"
  cloud:
    config:
      enabled: false
      override-none: true
      fail-fast: true
      import-check-enabled: false   # ? Add this to disable the import check
      retry:
        max-attempts: 5
        initial-interval: 2000
        multiplier: 1.5
dms:
  baseurl: Please get data
